module Handler.Admin
    ( getAdminR
    , getAdminBoardsR
    , getAdminBoardNewR
    , getAdminBoardR
    , postAdminBoardsR
    , postAdminBoardR
    , getAdminCompaniesR
    , getAdminCompanyNewR
    , getAdminCompanyR
    , postAdminCompaniesR
    , postAdminCompanyR
    , getAdminCompanyCategoriesR
    , getAdminCompanyCategoryNewR
    , getAdminCompanyCategoryR
    , postAdminCompanyCategoriesR
    , postAdminCompanyCategoryR
    , getAdminUsersR
    , getAdminUserNewR
    , getAdminUserR
    , postAdminUsersR
    , postAdminUserR
    , getAdminSettingsR
    , getAdminSettingNewR
    , getAdminSettingR
    , postAdminSettingsR
    , getAdminAdsR
    , getAdminAdNewR
    , getAdminAdR
    , postAdminAdsR
    , postAdminAdR
    , getAdminModerationR
    , postAdminModerationActionR
    , getAdminModerationLogsR
    ) where

import Handler.Admin.Ads
import Handler.Admin.Boards
import Handler.Admin.Companies
import Handler.Admin.Dashboard
import Handler.Admin.Moderation
import Handler.Admin.Settings
import Handler.Admin.Users
