Default: &defaults
  database: hkforum.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hkforum_test.sqlite3
  <<: *defaults

Staging:
  database: hkforum_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hkforum_production.sqlite3
  poolsize: 100
  <<: *defaults
