Default: &defaults
  database: my-project.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: my-project_test.sqlite3
  <<: *defaults

Staging:
  database: my-project_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: my-project_production.sqlite3
  poolsize: 100
  <<: *defaults
